name: dart_fpm
description: A Fast CGI Process Manager for dart
version: 0.0.1
#author: Benjamin Jesuiter <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  redstone: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
