name: dart_fpm
description: A FastCGI Process Manager(fpm) for dart.
version: 0.0.1
author: Benjamin Jesuiter <bjesuiter@gmail.com>
homepage: https://github.com/bjesuiter/dart_fpm

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  enums: 0.2.5
  logging_handlers: 0.8.0
  worker: 0.5.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
